apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "age-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: age-secret-controller
  {{- include "age-secrets.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ageSecretController.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.ageSecretController.strategy.rollingUpdate.maxSurge | quote }}
      maxUnavailable: {{ .Values.ageSecretController.strategy.rollingUpdate.maxUnavailable | quote
  selector:
    matchLabels:
      app: age-secret-controller
    {{- include "age-secrets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: age-secret-controller
      {{- include "age-secrets.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "age-secrets.fullname" . }}
      containers:
        - name: controller
          image: {{ .Values.ageSecretController.controller.image.repository }}:{{ .Values.ageSecretController.controller.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.ageSecretController.controller.imagePullPolicy }}
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources: {{- toYaml .Values.ageSecretController.controller.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.ageSecretController.controller.containerSecurityContext | nindent 12 }}
          args:
            - --leader-elect={{ default true .Values.ageSecretController.leaderElection.enabled }}
            - --leader-election-namespace={{ default .Release.Namespace .Values.ageSecretController.leaderElection.namespace }}
            {{- if .Values.keyNamespaces }}
            - --key-namespace={{ .Values.keyNamespaces }}
            {{- end }}
            - --metrics-bind-address=:{{ .Values.metricsService.bindAddress }}
            - --metrics-secure={{ .Values.metricsService.secure }}
            - --metrics-auth={{ .Values.metricsService.auth }}
            
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "age-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "age-secrets.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "age-secrets.fullname" . }}
  labels:
    {{- include "age-secrets.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - security.age.io
    resources:
      - agesecrets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - security.age.io
    resources:
      - agesecrets/status
    verbs:
      - get
      - update
      - patch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "age-secrets.fullname" . }}
  labels:
    {{- include "age-secrets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "age-secrets.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "age-secrets.fullname" . }}
    namespace: {{ .Release.Namespace }}
