{{- if .Values.ServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "age-secrets.fullname" . }}-monitor
  namespace: cattle-monitoring-system
  labels:
    app: age-secret-controller
    release: rancher-monitoring
  {{- include "age-secrets.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - age-system
  endpoints:
    - port: {{ .Values.metrics.portName }}
      path: {{ .Values.metrics.path }}
      scheme: {{ .Values.metrics.monitor.scheme }}
      honorLabels: {{ .Values.metrics.monitor.honorLabels }}
      tlsConfig:
        insecureSkipVerify: {{ .Values.metrics.monitor.tls.insecureSkipVerify }}
        serverName: {{ .Values.metrics.monitor.tls.serverName }}
{{- end }
  selector:
    matchLabels:
      app.kubernetes.io/name: age-secret-operator
      {{- include "age-secrets.selectorLabels" . | nindent 6 }}
{{- end }}

